//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUI.ServiceProveedor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Proveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdproveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_provField;
        
        private int Numero_provField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoProvField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Idproveedor {
            get {
                return this.IdproveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdproveedorField, value) != true)) {
                    this.IdproveedorField = value;
                    this.RaisePropertyChanged("Idproveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre_prov {
            get {
                return this.Nombre_provField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_provField, value) != true)) {
                    this.Nombre_provField = value;
                    this.RaisePropertyChanged("Nombre_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Numero_prov {
            get {
                return this.Numero_provField;
            }
            set {
                if ((this.Numero_provField.Equals(value) != true)) {
                    this.Numero_provField = value;
                    this.RaisePropertyChanged("Numero_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CorreoProv {
            get {
                return this.CorreoProvField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoProvField, value) != true)) {
                    this.CorreoProvField = value;
                    this.RaisePropertyChanged("CorreoProv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProveedor.WebServiceProveedorSoap")]
    public interface WebServiceProveedorSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento proveedor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioinsertarProveedor", ReplyAction="*")]
        CapaUI.ServiceProveedor.ServicioinsertarProveedorResponse ServicioinsertarProveedor(CapaUI.ServiceProveedor.ServicioinsertarProveedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioinsertarProveedor", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceProveedor.ServicioinsertarProveedorResponse> ServicioinsertarProveedorAsync(CapaUI.ServiceProveedor.ServicioinsertarProveedorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idproveedor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiciobuscaProv", ReplyAction="*")]
        CapaUI.ServiceProveedor.ServiciobuscaProvResponse ServiciobuscaProv(CapaUI.ServiceProveedor.ServiciobuscaProvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiciobuscaProv", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceProveedor.ServiciobuscaProvResponse> ServiciobuscaProvAsync(CapaUI.ServiceProveedor.ServiciobuscaProvRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idproveedor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiciobuscaConcidencia", ReplyAction="*")]
        CapaUI.ServiceProveedor.ServiciobuscaConcidenciaResponse ServiciobuscaConcidencia(CapaUI.ServiceProveedor.ServiciobuscaConcidenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiciobuscaConcidencia", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceProveedor.ServiciobuscaConcidenciaResponse> ServiciobuscaConcidenciaAsync(CapaUI.ServiceProveedor.ServiciobuscaConcidenciaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IDaborrar del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioeliminarProv", ReplyAction="*")]
        CapaUI.ServiceProveedor.ServicioeliminarProvResponse ServicioeliminarProv(CapaUI.ServiceProveedor.ServicioeliminarProvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioeliminarProv", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceProveedor.ServicioeliminarProvResponse> ServicioeliminarProvAsync(CapaUI.ServiceProveedor.ServicioeliminarProvRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento proveedor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServcioactualizarProv", ReplyAction="*")]
        CapaUI.ServiceProveedor.ServcioactualizarProvResponse ServcioactualizarProv(CapaUI.ServiceProveedor.ServcioactualizarProvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServcioactualizarProv", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceProveedor.ServcioactualizarProvResponse> ServcioactualizarProvAsync(CapaUI.ServiceProveedor.ServcioactualizarProvRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioinsertarProveedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioinsertarProveedor", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProveedor.ServicioinsertarProveedorRequestBody Body;
        
        public ServicioinsertarProveedorRequest() {
        }
        
        public ServicioinsertarProveedorRequest(CapaUI.ServiceProveedor.ServicioinsertarProveedorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioinsertarProveedorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceProveedor.Proveedor proveedor;
        
        public ServicioinsertarProveedorRequestBody() {
        }
        
        public ServicioinsertarProveedorRequestBody(CapaUI.ServiceProveedor.Proveedor proveedor) {
            this.proveedor = proveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioinsertarProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioinsertarProveedorResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProveedor.ServicioinsertarProveedorResponseBody Body;
        
        public ServicioinsertarProveedorResponse() {
        }
        
        public ServicioinsertarProveedorResponse(CapaUI.ServiceProveedor.ServicioinsertarProveedorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioinsertarProveedorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ServicioinsertarProveedorResult;
        
        public ServicioinsertarProveedorResponseBody() {
        }
        
        public ServicioinsertarProveedorResponseBody(bool ServicioinsertarProveedorResult) {
            this.ServicioinsertarProveedorResult = ServicioinsertarProveedorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiciobuscaProvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiciobuscaProv", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProveedor.ServiciobuscaProvRequestBody Body;
        
        public ServiciobuscaProvRequest() {
        }
        
        public ServiciobuscaProvRequest(CapaUI.ServiceProveedor.ServiciobuscaProvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiciobuscaProvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idproveedor;
        
        public ServiciobuscaProvRequestBody() {
        }
        
        public ServiciobuscaProvRequestBody(string idproveedor) {
            this.idproveedor = idproveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiciobuscaProvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiciobuscaProvResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProveedor.ServiciobuscaProvResponseBody Body;
        
        public ServiciobuscaProvResponse() {
        }
        
        public ServiciobuscaProvResponse(CapaUI.ServiceProveedor.ServiciobuscaProvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiciobuscaProvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceProveedor.Proveedor ServiciobuscaProvResult;
        
        public ServiciobuscaProvResponseBody() {
        }
        
        public ServiciobuscaProvResponseBody(CapaUI.ServiceProveedor.Proveedor ServiciobuscaProvResult) {
            this.ServiciobuscaProvResult = ServiciobuscaProvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiciobuscaConcidenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiciobuscaConcidencia", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProveedor.ServiciobuscaConcidenciaRequestBody Body;
        
        public ServiciobuscaConcidenciaRequest() {
        }
        
        public ServiciobuscaConcidenciaRequest(CapaUI.ServiceProveedor.ServiciobuscaConcidenciaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiciobuscaConcidenciaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idproveedor;
        
        public ServiciobuscaConcidenciaRequestBody() {
        }
        
        public ServiciobuscaConcidenciaRequestBody(string idproveedor) {
            this.idproveedor = idproveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiciobuscaConcidenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiciobuscaConcidenciaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProveedor.ServiciobuscaConcidenciaResponseBody Body;
        
        public ServiciobuscaConcidenciaResponse() {
        }
        
        public ServiciobuscaConcidenciaResponse(CapaUI.ServiceProveedor.ServiciobuscaConcidenciaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiciobuscaConcidenciaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceProveedor.Proveedor ServiciobuscaConcidenciaResult;
        
        public ServiciobuscaConcidenciaResponseBody() {
        }
        
        public ServiciobuscaConcidenciaResponseBody(CapaUI.ServiceProveedor.Proveedor ServiciobuscaConcidenciaResult) {
            this.ServiciobuscaConcidenciaResult = ServiciobuscaConcidenciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioeliminarProvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioeliminarProv", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProveedor.ServicioeliminarProvRequestBody Body;
        
        public ServicioeliminarProvRequest() {
        }
        
        public ServicioeliminarProvRequest(CapaUI.ServiceProveedor.ServicioeliminarProvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioeliminarProvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDaborrar;
        
        public ServicioeliminarProvRequestBody() {
        }
        
        public ServicioeliminarProvRequestBody(string IDaborrar) {
            this.IDaborrar = IDaborrar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioeliminarProvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioeliminarProvResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProveedor.ServicioeliminarProvResponseBody Body;
        
        public ServicioeliminarProvResponse() {
        }
        
        public ServicioeliminarProvResponse(CapaUI.ServiceProveedor.ServicioeliminarProvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ServicioeliminarProvResponseBody {
        
        public ServicioeliminarProvResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServcioactualizarProvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServcioactualizarProv", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProveedor.ServcioactualizarProvRequestBody Body;
        
        public ServcioactualizarProvRequest() {
        }
        
        public ServcioactualizarProvRequest(CapaUI.ServiceProveedor.ServcioactualizarProvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServcioactualizarProvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceProveedor.Proveedor proveedor;
        
        public ServcioactualizarProvRequestBody() {
        }
        
        public ServcioactualizarProvRequestBody(CapaUI.ServiceProveedor.Proveedor proveedor) {
            this.proveedor = proveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServcioactualizarProvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServcioactualizarProvResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProveedor.ServcioactualizarProvResponseBody Body;
        
        public ServcioactualizarProvResponse() {
        }
        
        public ServcioactualizarProvResponse(CapaUI.ServiceProveedor.ServcioactualizarProvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ServcioactualizarProvResponseBody {
        
        public ServcioactualizarProvResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceProveedorSoapChannel : CapaUI.ServiceProveedor.WebServiceProveedorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceProveedorSoapClient : System.ServiceModel.ClientBase<CapaUI.ServiceProveedor.WebServiceProveedorSoap>, CapaUI.ServiceProveedor.WebServiceProveedorSoap {
        
        public WebServiceProveedorSoapClient() {
        }
        
        public WebServiceProveedorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceProveedorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProveedorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProveedorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceProveedor.ServicioinsertarProveedorResponse CapaUI.ServiceProveedor.WebServiceProveedorSoap.ServicioinsertarProveedor(CapaUI.ServiceProveedor.ServicioinsertarProveedorRequest request) {
            return base.Channel.ServicioinsertarProveedor(request);
        }
        
        public bool ServicioinsertarProveedor(CapaUI.ServiceProveedor.Proveedor proveedor) {
            CapaUI.ServiceProveedor.ServicioinsertarProveedorRequest inValue = new CapaUI.ServiceProveedor.ServicioinsertarProveedorRequest();
            inValue.Body = new CapaUI.ServiceProveedor.ServicioinsertarProveedorRequestBody();
            inValue.Body.proveedor = proveedor;
            CapaUI.ServiceProveedor.ServicioinsertarProveedorResponse retVal = ((CapaUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServicioinsertarProveedor(inValue);
            return retVal.Body.ServicioinsertarProveedorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceProveedor.ServicioinsertarProveedorResponse> CapaUI.ServiceProveedor.WebServiceProveedorSoap.ServicioinsertarProveedorAsync(CapaUI.ServiceProveedor.ServicioinsertarProveedorRequest request) {
            return base.Channel.ServicioinsertarProveedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceProveedor.ServicioinsertarProveedorResponse> ServicioinsertarProveedorAsync(CapaUI.ServiceProveedor.Proveedor proveedor) {
            CapaUI.ServiceProveedor.ServicioinsertarProveedorRequest inValue = new CapaUI.ServiceProveedor.ServicioinsertarProveedorRequest();
            inValue.Body = new CapaUI.ServiceProveedor.ServicioinsertarProveedorRequestBody();
            inValue.Body.proveedor = proveedor;
            return ((CapaUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServicioinsertarProveedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceProveedor.ServiciobuscaProvResponse CapaUI.ServiceProveedor.WebServiceProveedorSoap.ServiciobuscaProv(CapaUI.ServiceProveedor.ServiciobuscaProvRequest request) {
            return base.Channel.ServiciobuscaProv(request);
        }
        
        public CapaUI.ServiceProveedor.Proveedor ServiciobuscaProv(string idproveedor) {
            CapaUI.ServiceProveedor.ServiciobuscaProvRequest inValue = new CapaUI.ServiceProveedor.ServiciobuscaProvRequest();
            inValue.Body = new CapaUI.ServiceProveedor.ServiciobuscaProvRequestBody();
            inValue.Body.idproveedor = idproveedor;
            CapaUI.ServiceProveedor.ServiciobuscaProvResponse retVal = ((CapaUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServiciobuscaProv(inValue);
            return retVal.Body.ServiciobuscaProvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceProveedor.ServiciobuscaProvResponse> CapaUI.ServiceProveedor.WebServiceProveedorSoap.ServiciobuscaProvAsync(CapaUI.ServiceProveedor.ServiciobuscaProvRequest request) {
            return base.Channel.ServiciobuscaProvAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceProveedor.ServiciobuscaProvResponse> ServiciobuscaProvAsync(string idproveedor) {
            CapaUI.ServiceProveedor.ServiciobuscaProvRequest inValue = new CapaUI.ServiceProveedor.ServiciobuscaProvRequest();
            inValue.Body = new CapaUI.ServiceProveedor.ServiciobuscaProvRequestBody();
            inValue.Body.idproveedor = idproveedor;
            return ((CapaUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServiciobuscaProvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceProveedor.ServiciobuscaConcidenciaResponse CapaUI.ServiceProveedor.WebServiceProveedorSoap.ServiciobuscaConcidencia(CapaUI.ServiceProveedor.ServiciobuscaConcidenciaRequest request) {
            return base.Channel.ServiciobuscaConcidencia(request);
        }
        
        public CapaUI.ServiceProveedor.Proveedor ServiciobuscaConcidencia(string idproveedor) {
            CapaUI.ServiceProveedor.ServiciobuscaConcidenciaRequest inValue = new CapaUI.ServiceProveedor.ServiciobuscaConcidenciaRequest();
            inValue.Body = new CapaUI.ServiceProveedor.ServiciobuscaConcidenciaRequestBody();
            inValue.Body.idproveedor = idproveedor;
            CapaUI.ServiceProveedor.ServiciobuscaConcidenciaResponse retVal = ((CapaUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServiciobuscaConcidencia(inValue);
            return retVal.Body.ServiciobuscaConcidenciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceProveedor.ServiciobuscaConcidenciaResponse> CapaUI.ServiceProveedor.WebServiceProveedorSoap.ServiciobuscaConcidenciaAsync(CapaUI.ServiceProveedor.ServiciobuscaConcidenciaRequest request) {
            return base.Channel.ServiciobuscaConcidenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceProveedor.ServiciobuscaConcidenciaResponse> ServiciobuscaConcidenciaAsync(string idproveedor) {
            CapaUI.ServiceProveedor.ServiciobuscaConcidenciaRequest inValue = new CapaUI.ServiceProveedor.ServiciobuscaConcidenciaRequest();
            inValue.Body = new CapaUI.ServiceProveedor.ServiciobuscaConcidenciaRequestBody();
            inValue.Body.idproveedor = idproveedor;
            return ((CapaUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServiciobuscaConcidenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceProveedor.ServicioeliminarProvResponse CapaUI.ServiceProveedor.WebServiceProveedorSoap.ServicioeliminarProv(CapaUI.ServiceProveedor.ServicioeliminarProvRequest request) {
            return base.Channel.ServicioeliminarProv(request);
        }
        
        public void ServicioeliminarProv(string IDaborrar) {
            CapaUI.ServiceProveedor.ServicioeliminarProvRequest inValue = new CapaUI.ServiceProveedor.ServicioeliminarProvRequest();
            inValue.Body = new CapaUI.ServiceProveedor.ServicioeliminarProvRequestBody();
            inValue.Body.IDaborrar = IDaborrar;
            CapaUI.ServiceProveedor.ServicioeliminarProvResponse retVal = ((CapaUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServicioeliminarProv(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceProveedor.ServicioeliminarProvResponse> CapaUI.ServiceProveedor.WebServiceProveedorSoap.ServicioeliminarProvAsync(CapaUI.ServiceProveedor.ServicioeliminarProvRequest request) {
            return base.Channel.ServicioeliminarProvAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceProveedor.ServicioeliminarProvResponse> ServicioeliminarProvAsync(string IDaborrar) {
            CapaUI.ServiceProveedor.ServicioeliminarProvRequest inValue = new CapaUI.ServiceProveedor.ServicioeliminarProvRequest();
            inValue.Body = new CapaUI.ServiceProveedor.ServicioeliminarProvRequestBody();
            inValue.Body.IDaborrar = IDaborrar;
            return ((CapaUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServicioeliminarProvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceProveedor.ServcioactualizarProvResponse CapaUI.ServiceProveedor.WebServiceProveedorSoap.ServcioactualizarProv(CapaUI.ServiceProveedor.ServcioactualizarProvRequest request) {
            return base.Channel.ServcioactualizarProv(request);
        }
        
        public void ServcioactualizarProv(CapaUI.ServiceProveedor.Proveedor proveedor) {
            CapaUI.ServiceProveedor.ServcioactualizarProvRequest inValue = new CapaUI.ServiceProveedor.ServcioactualizarProvRequest();
            inValue.Body = new CapaUI.ServiceProveedor.ServcioactualizarProvRequestBody();
            inValue.Body.proveedor = proveedor;
            CapaUI.ServiceProveedor.ServcioactualizarProvResponse retVal = ((CapaUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServcioactualizarProv(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceProveedor.ServcioactualizarProvResponse> CapaUI.ServiceProveedor.WebServiceProveedorSoap.ServcioactualizarProvAsync(CapaUI.ServiceProveedor.ServcioactualizarProvRequest request) {
            return base.Channel.ServcioactualizarProvAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceProveedor.ServcioactualizarProvResponse> ServcioactualizarProvAsync(CapaUI.ServiceProveedor.Proveedor proveedor) {
            CapaUI.ServiceProveedor.ServcioactualizarProvRequest inValue = new CapaUI.ServiceProveedor.ServcioactualizarProvRequest();
            inValue.Body = new CapaUI.ServiceProveedor.ServcioactualizarProvRequestBody();
            inValue.Body.proveedor = proveedor;
            return ((CapaUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServcioactualizarProvAsync(inValue);
        }
    }
}
