//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUI.ServiceUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuario.WebServiceUsuarioSoap")]
    public interface WebServiceUsuarioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioInsertarUsuario", ReplyAction="*")]
        CapaUI.ServiceUsuario.ServicioInsertarUsuarioResponse ServicioInsertarUsuario(CapaUI.ServiceUsuario.ServicioInsertarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioInsertarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceUsuario.ServicioInsertarUsuarioResponse> ServicioInsertarUsuarioAsync(CapaUI.ServiceUsuario.ServicioInsertarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idUsuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioBuscarUsuario", ReplyAction="*")]
        CapaUI.ServiceUsuario.ServicioBuscarUsuarioResponse ServicioBuscarUsuario(CapaUI.ServiceUsuario.ServicioBuscarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioBuscarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceUsuario.ServicioBuscarUsuarioResponse> ServicioBuscarUsuarioAsync(CapaUI.ServiceUsuario.ServicioBuscarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IDaborrar del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioEliminarUsuario", ReplyAction="*")]
        CapaUI.ServiceUsuario.ServicioEliminarUsuarioResponse ServicioEliminarUsuario(CapaUI.ServiceUsuario.ServicioEliminarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioEliminarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceUsuario.ServicioEliminarUsuarioResponse> ServicioEliminarUsuarioAsync(CapaUI.ServiceUsuario.ServicioEliminarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioActualizarUsuario", ReplyAction="*")]
        CapaUI.ServiceUsuario.ServicioActualizarUsuarioResponse ServicioActualizarUsuario(CapaUI.ServiceUsuario.ServicioActualizarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioActualizarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceUsuario.ServicioActualizarUsuarioResponse> ServicioActualizarUsuarioAsync(CapaUI.ServiceUsuario.ServicioActualizarUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioInsertarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioInsertarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceUsuario.ServicioInsertarUsuarioRequestBody Body;
        
        public ServicioInsertarUsuarioRequest() {
        }
        
        public ServicioInsertarUsuarioRequest(CapaUI.ServiceUsuario.ServicioInsertarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioInsertarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceUsuario.Usuario usuario;
        
        public ServicioInsertarUsuarioRequestBody() {
        }
        
        public ServicioInsertarUsuarioRequestBody(CapaUI.ServiceUsuario.Usuario usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioInsertarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioInsertarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceUsuario.ServicioInsertarUsuarioResponseBody Body;
        
        public ServicioInsertarUsuarioResponse() {
        }
        
        public ServicioInsertarUsuarioResponse(CapaUI.ServiceUsuario.ServicioInsertarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioInsertarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ServicioInsertarUsuarioResult;
        
        public ServicioInsertarUsuarioResponseBody() {
        }
        
        public ServicioInsertarUsuarioResponseBody(bool ServicioInsertarUsuarioResult) {
            this.ServicioInsertarUsuarioResult = ServicioInsertarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioBuscarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioBuscarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceUsuario.ServicioBuscarUsuarioRequestBody Body;
        
        public ServicioBuscarUsuarioRequest() {
        }
        
        public ServicioBuscarUsuarioRequest(CapaUI.ServiceUsuario.ServicioBuscarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioBuscarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idUsuario;
        
        public ServicioBuscarUsuarioRequestBody() {
        }
        
        public ServicioBuscarUsuarioRequestBody(string idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioBuscarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioBuscarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceUsuario.ServicioBuscarUsuarioResponseBody Body;
        
        public ServicioBuscarUsuarioResponse() {
        }
        
        public ServicioBuscarUsuarioResponse(CapaUI.ServiceUsuario.ServicioBuscarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioBuscarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceUsuario.Usuario ServicioBuscarUsuarioResult;
        
        public ServicioBuscarUsuarioResponseBody() {
        }
        
        public ServicioBuscarUsuarioResponseBody(CapaUI.ServiceUsuario.Usuario ServicioBuscarUsuarioResult) {
            this.ServicioBuscarUsuarioResult = ServicioBuscarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioEliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioEliminarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceUsuario.ServicioEliminarUsuarioRequestBody Body;
        
        public ServicioEliminarUsuarioRequest() {
        }
        
        public ServicioEliminarUsuarioRequest(CapaUI.ServiceUsuario.ServicioEliminarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioEliminarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDaborrar;
        
        public ServicioEliminarUsuarioRequestBody() {
        }
        
        public ServicioEliminarUsuarioRequestBody(string IDaborrar) {
            this.IDaborrar = IDaborrar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioEliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioEliminarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceUsuario.ServicioEliminarUsuarioResponseBody Body;
        
        public ServicioEliminarUsuarioResponse() {
        }
        
        public ServicioEliminarUsuarioResponse(CapaUI.ServiceUsuario.ServicioEliminarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ServicioEliminarUsuarioResponseBody {
        
        public ServicioEliminarUsuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioActualizarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioActualizarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceUsuario.ServicioActualizarUsuarioRequestBody Body;
        
        public ServicioActualizarUsuarioRequest() {
        }
        
        public ServicioActualizarUsuarioRequest(CapaUI.ServiceUsuario.ServicioActualizarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioActualizarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceUsuario.Usuario usuario;
        
        public ServicioActualizarUsuarioRequestBody() {
        }
        
        public ServicioActualizarUsuarioRequestBody(CapaUI.ServiceUsuario.Usuario usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioActualizarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioActualizarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceUsuario.ServicioActualizarUsuarioResponseBody Body;
        
        public ServicioActualizarUsuarioResponse() {
        }
        
        public ServicioActualizarUsuarioResponse(CapaUI.ServiceUsuario.ServicioActualizarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ServicioActualizarUsuarioResponseBody {
        
        public ServicioActualizarUsuarioResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUsuarioSoapChannel : CapaUI.ServiceUsuario.WebServiceUsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUsuarioSoapClient : System.ServiceModel.ClientBase<CapaUI.ServiceUsuario.WebServiceUsuarioSoap>, CapaUI.ServiceUsuario.WebServiceUsuarioSoap {
        
        public WebServiceUsuarioSoapClient() {
        }
        
        public WebServiceUsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceUsuario.ServicioInsertarUsuarioResponse CapaUI.ServiceUsuario.WebServiceUsuarioSoap.ServicioInsertarUsuario(CapaUI.ServiceUsuario.ServicioInsertarUsuarioRequest request) {
            return base.Channel.ServicioInsertarUsuario(request);
        }
        
        public bool ServicioInsertarUsuario(CapaUI.ServiceUsuario.Usuario usuario) {
            CapaUI.ServiceUsuario.ServicioInsertarUsuarioRequest inValue = new CapaUI.ServiceUsuario.ServicioInsertarUsuarioRequest();
            inValue.Body = new CapaUI.ServiceUsuario.ServicioInsertarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            CapaUI.ServiceUsuario.ServicioInsertarUsuarioResponse retVal = ((CapaUI.ServiceUsuario.WebServiceUsuarioSoap)(this)).ServicioInsertarUsuario(inValue);
            return retVal.Body.ServicioInsertarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceUsuario.ServicioInsertarUsuarioResponse> CapaUI.ServiceUsuario.WebServiceUsuarioSoap.ServicioInsertarUsuarioAsync(CapaUI.ServiceUsuario.ServicioInsertarUsuarioRequest request) {
            return base.Channel.ServicioInsertarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceUsuario.ServicioInsertarUsuarioResponse> ServicioInsertarUsuarioAsync(CapaUI.ServiceUsuario.Usuario usuario) {
            CapaUI.ServiceUsuario.ServicioInsertarUsuarioRequest inValue = new CapaUI.ServiceUsuario.ServicioInsertarUsuarioRequest();
            inValue.Body = new CapaUI.ServiceUsuario.ServicioInsertarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            return ((CapaUI.ServiceUsuario.WebServiceUsuarioSoap)(this)).ServicioInsertarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceUsuario.ServicioBuscarUsuarioResponse CapaUI.ServiceUsuario.WebServiceUsuarioSoap.ServicioBuscarUsuario(CapaUI.ServiceUsuario.ServicioBuscarUsuarioRequest request) {
            return base.Channel.ServicioBuscarUsuario(request);
        }
        
        public CapaUI.ServiceUsuario.Usuario ServicioBuscarUsuario(string idUsuario) {
            CapaUI.ServiceUsuario.ServicioBuscarUsuarioRequest inValue = new CapaUI.ServiceUsuario.ServicioBuscarUsuarioRequest();
            inValue.Body = new CapaUI.ServiceUsuario.ServicioBuscarUsuarioRequestBody();
            inValue.Body.idUsuario = idUsuario;
            CapaUI.ServiceUsuario.ServicioBuscarUsuarioResponse retVal = ((CapaUI.ServiceUsuario.WebServiceUsuarioSoap)(this)).ServicioBuscarUsuario(inValue);
            return retVal.Body.ServicioBuscarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceUsuario.ServicioBuscarUsuarioResponse> CapaUI.ServiceUsuario.WebServiceUsuarioSoap.ServicioBuscarUsuarioAsync(CapaUI.ServiceUsuario.ServicioBuscarUsuarioRequest request) {
            return base.Channel.ServicioBuscarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceUsuario.ServicioBuscarUsuarioResponse> ServicioBuscarUsuarioAsync(string idUsuario) {
            CapaUI.ServiceUsuario.ServicioBuscarUsuarioRequest inValue = new CapaUI.ServiceUsuario.ServicioBuscarUsuarioRequest();
            inValue.Body = new CapaUI.ServiceUsuario.ServicioBuscarUsuarioRequestBody();
            inValue.Body.idUsuario = idUsuario;
            return ((CapaUI.ServiceUsuario.WebServiceUsuarioSoap)(this)).ServicioBuscarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceUsuario.ServicioEliminarUsuarioResponse CapaUI.ServiceUsuario.WebServiceUsuarioSoap.ServicioEliminarUsuario(CapaUI.ServiceUsuario.ServicioEliminarUsuarioRequest request) {
            return base.Channel.ServicioEliminarUsuario(request);
        }
        
        public void ServicioEliminarUsuario(string IDaborrar) {
            CapaUI.ServiceUsuario.ServicioEliminarUsuarioRequest inValue = new CapaUI.ServiceUsuario.ServicioEliminarUsuarioRequest();
            inValue.Body = new CapaUI.ServiceUsuario.ServicioEliminarUsuarioRequestBody();
            inValue.Body.IDaborrar = IDaborrar;
            CapaUI.ServiceUsuario.ServicioEliminarUsuarioResponse retVal = ((CapaUI.ServiceUsuario.WebServiceUsuarioSoap)(this)).ServicioEliminarUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceUsuario.ServicioEliminarUsuarioResponse> CapaUI.ServiceUsuario.WebServiceUsuarioSoap.ServicioEliminarUsuarioAsync(CapaUI.ServiceUsuario.ServicioEliminarUsuarioRequest request) {
            return base.Channel.ServicioEliminarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceUsuario.ServicioEliminarUsuarioResponse> ServicioEliminarUsuarioAsync(string IDaborrar) {
            CapaUI.ServiceUsuario.ServicioEliminarUsuarioRequest inValue = new CapaUI.ServiceUsuario.ServicioEliminarUsuarioRequest();
            inValue.Body = new CapaUI.ServiceUsuario.ServicioEliminarUsuarioRequestBody();
            inValue.Body.IDaborrar = IDaborrar;
            return ((CapaUI.ServiceUsuario.WebServiceUsuarioSoap)(this)).ServicioEliminarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceUsuario.ServicioActualizarUsuarioResponse CapaUI.ServiceUsuario.WebServiceUsuarioSoap.ServicioActualizarUsuario(CapaUI.ServiceUsuario.ServicioActualizarUsuarioRequest request) {
            return base.Channel.ServicioActualizarUsuario(request);
        }
        
        public void ServicioActualizarUsuario(CapaUI.ServiceUsuario.Usuario usuario) {
            CapaUI.ServiceUsuario.ServicioActualizarUsuarioRequest inValue = new CapaUI.ServiceUsuario.ServicioActualizarUsuarioRequest();
            inValue.Body = new CapaUI.ServiceUsuario.ServicioActualizarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            CapaUI.ServiceUsuario.ServicioActualizarUsuarioResponse retVal = ((CapaUI.ServiceUsuario.WebServiceUsuarioSoap)(this)).ServicioActualizarUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceUsuario.ServicioActualizarUsuarioResponse> CapaUI.ServiceUsuario.WebServiceUsuarioSoap.ServicioActualizarUsuarioAsync(CapaUI.ServiceUsuario.ServicioActualizarUsuarioRequest request) {
            return base.Channel.ServicioActualizarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceUsuario.ServicioActualizarUsuarioResponse> ServicioActualizarUsuarioAsync(CapaUI.ServiceUsuario.Usuario usuario) {
            CapaUI.ServiceUsuario.ServicioActualizarUsuarioRequest inValue = new CapaUI.ServiceUsuario.ServicioActualizarUsuarioRequest();
            inValue.Body = new CapaUI.ServiceUsuario.ServicioActualizarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            return ((CapaUI.ServiceUsuario.WebServiceUsuarioSoap)(this)).ServicioActualizarUsuarioAsync(inValue);
        }
    }
}
